routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Foundation\Auth\EmailVerificationRequest;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Auth::routes();
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/tim-kiem', [App\Http\Controllers\CategoryController::class, 'search'])->name('search');
Route::get('/danh-muc', [App\Http\Controllers\CategoryController::class, 'all'])->name('category.all');
Route::get('/logout', [App\Http\Controllers\HomeController::class, 'logout'])->name('logout');
Route::post('/auth/register', [App\Http\Controllers\AuthController::class, 'register'])->name('auth.register');
Route::get('/email/verify/{id}/{hash}', function (EmailVerificationRequest $request) {
    $request->fulfill();
    return redirect('/home');
})->middleware(['auth', 'signed'])->name('verification.verify');
Route::prefix('admin')->middleware(['auth.admin'])->group(function() {
    Route::get('/', [App\Http\Controllers\Admin\DashboardController::class, 'index'])->name('admin.dashboard');
    Route::get('/logout', [App\Http\Controllers\Admin\DashboardController::class, 'logout'])->name('admin.logout');
    // store
    Route::get('/store/create', [App\Http\Controllers\Admin\StoreController::class, 'create'])->name('admin.store.create');
    Route::post('/store/store', [App\Http\Controllers\Admin\StoreController::class, 'store'])->name('admin.store.store');
    Route::get('/store/edit/{id}', [App\Http\Controllers\Admin\StoreController::class, 'edit'])->name('admin.store.edit');
    Route::post('/store/update', [App\Http\Controllers\Admin\StoreController::class, 'update'])->name('admin.store.update');
    Route::get('/store/approve/{id}', [App\Http\Controllers\Admin\StoreController::class, 'approve'])->name('admin.store.approve');
    Route::get('/store/show', [App\Http\Controllers\Admin\StoreController::class, 'show'])->name('admin.store.show');
    // user
    Route::get('/user', [App\Http\Controllers\Admin\UserController::class, 'index'])->name('admin.user.index');
    Route::post('/user/update', [App\Http\Controllers\Admin\UserController::class, 'show'])->name('admin.user.update');
    Route::get('/user/edit/{id}', [App\Http\Controllers\Admin\UserController::class, 'edit'])->name('admin.user.edit');
    Route::get('/user/approve/{id}', [App\Http\Controllers\Admin\UserController::class, 'approve'])->name('admin.user.approve');
    //post
    Route::get('/post/show', [App\Http\Controllers\Admin\PostController::class, 'show'])->name('admin.post.show');
    Route::post('/post/update', [App\Http\Controllers\Admin\PostController::class, 'update'])->name('admin.post.update');
    Route::get('/post/edit/{id}', [App\Http\Controllers\Admin\PostController::class, 'edit'])->name('admin.post.edit');
    Route::get('/post/store', [App\Http\Controllers\Admin\PostController::class, 'create'])->name('admin.post.store');
    Route::post('/post/store', [App\Http\Controllers\Admin\PostController::class, 'store'])->name('admin.post.store');
    Route::get('/post/destroy/{id}', [App\Http\Controllers\Admin\PostController::class, 'destroy'])->name('admin.post.destroy');
    //postCategory
    Route::get('/postcategory/show', [App\Http\Controllers\Admin\PostCategoryController::class, 'show'])->name('admin.postcategory.show');
    Route::post('/postcategory/update', [App\Http\Controllers\Admin\PostCategoryController::class, 'update'])->name('admin.postcategory.update');
    Route::get('/postcategory/edit/{id}', [App\Http\Controllers\Admin\PostCategoryController::class, 'edit'])->name('admin.postcategory.edit');
    Route::get('/postcategory/store', [App\Http\Controllers\Admin\PostCategoryController::class, 'create'])->name('admin.postcategory.store');
    Route::post('/postcategory/store', [App\Http\Controllers\Admin\PostCategoryController::class, 'store'])->name('admin.postcategory.store');
    Route::get('/postcategory/destroy/{id}', [App\Http\Controllers\Admin\PostCategoryController::class, 'destroy'])->name('admin.postcategory.destroy');
    //Category
    Route::get('/category/show', [App\Http\Controllers\Admin\CategoryController::class, 'show'])->name('admin.category.show');
    Route::post('/category/update', [App\Http\Controllers\Admin\CategoryController::class, 'update'])->name('admin.category.update');
    Route::get('/category/edit/{id}', [App\Http\Controllers\Admin\CategoryController::class, 'edit'])->name('admin.category.edit');
    Route::get('/category/store', [App\Http\Controllers\Admin\CategoryController::class, 'create'])->name('admin.category.store');
    Route::post('/category/store', [App\Http\Controllers\Admin\CategoryController::class, 'store'])->name('admin.category.store');
    Route::get('/category/destroy/{id}', [App\Http\Controllers\Admin\CategoryController::class, 'destroy'])->name('admin.category.destroy');
    //Position
    Route::get('/position/show', [App\Http\Controllers\Admin\PositionController::class, 'show'])->name('admin.position.show');
    Route::post('/position/update', [App\Http\Controllers\Admin\PositionController::class, 'update'])->name('admin.position.update');
    Route::get('/position/edit/{id}', [App\Http\Controllers\Admin\PositionController::class, 'edit'])->name('admin.position.edit');
    Route::get('/position/store', [App\Http\Controllers\Admin\PositionController::class, 'create'])->name('admin.position.store');
    Route::post('/position/store', [App\Http\Controllers\Admin\PositionController::class, 'store'])->name('admin.position.store');
    Route::get('/position/destroy/{id}', [App\Http\Controllers\Admin\PositionController::class, 'destroy'])->name('admin.position.destroy');
});
Route::post('/subscribe', [App\Http\Controllers\UserController::class, 'subscribe'])->name('subscribe');
Route::get('/{alias}', [App\Http\Controllers\PostController::class, 'detail'])->name('post.detail');
Route::get('/tin-tuc/{alias}', [App\Http\Controllers\PostController::class, 'index'])->name('post.index');
Route::get('/cua-hang/{alias}', [App\Http\Controllers\StoreController::class, 'detail'])->name('store.detail');
Route::get('/dia-diem/{alias}', [App\Http\Controllers\PositionController::class, 'index'])->name('position.index');
Route::get('/danh-muc/{alias}', [App\Http\Controllers\CategoryController::class, 'index'])->name('category.index');
Route::any('/profile/edit', [App\Http\Controllers\UserController::class, 'profile'])->name('profile');

Route::post('/auth/login', [App\Http\Controllers\Auth\LoginController::class, 'submitLogin'])->name('auth.login');

Route::any('/ckfinder/connector', '\CKSource\CKFinderBridge\Controller\CKFinderController@requestAction')
    ->name('ckfinder_connector');

Route::any('/ckfinder/browser', '\CKSource\CKFinderBridge\Controller\CKFinderController@browserAction')
    ->name('ckfinder_browser');

Route::get('/auth/facebook/redirect', [App\Http\Controllers\Auth\SocialController::class, 'redirectFacebook'])->name('login-facebook');
Route::get('/auth/facebook/callback', [App\Http\Controllers\Auth\SocialController::class, 'callbackFacebook']);

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Category extends Model
{
    use HasFactory;
    protected $fillable = ['id', 'title', 'image', 'description', 'status','parent_id','slug'];
    public function stores() {
        if (in_array($this->slug,['thoi-trang'])) {
            return Store::where('type_id', 2)->get();
        }
        if (in_array($this->slug,['xuong'])) {
            return Store::where('type_id', 3)->get();
        }
        if (in_array($this->slug,['nguyen-lieu'])) {
            return Store::where('type_id', 1)->get();
        }
        $id = $this->id;
        $ids = Category::where(function($p)use($id){
            $p->where('id', $id)->orWhere('parent_id', $id);
        })->pluck('id');
        return Store::whereIn('id', CategoryStore::whereIn('category_id', $ids)->pluck('store_id'))->get();
    }
    public function parent() {
        return $this->belongsTo(Category::class);
    }
    public function children() {
        return $this->hasMany(Category::class,'parent_id');
    }
    public function getUrlAttribute() {
        return '/danh-muc/'.$this->slug;
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('admin.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->merge([
            'slug' => Str::slug($request->title),
            'image' => '/storage/'. $request->file_upload->store('userfiles/images', 'public')
        ]);
        $input = $request->except(['_token']);
        $category =  Category::create($input);
        return redirect()->route('admin.category.show')->with('success', 'Thêm danh mục cửa hàng thành công');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
        $categories = Category::all();
        return view('admin.category.show',['categories' => $categories]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $data = Category::find($id);
        return view('admin.category.edit', ['data' => $data]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $category = Category::find($request->id);
        $request->merge([
            'slug' => Str::slug($request->title),
            'image' => $request->file_upload ? ('/storage/'. $request->file_upload->store('userfiles/images', 'public')) : $category->image
        ]);
        $input = $request->except(['_token', 'id']);
        if ($category->update($input))
        {
            return redirect()->route('admin.category.show')->with('success', 'Sửa danh mục cửa hàng thành công');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $category = Category::find($id);
        if ($category->delete())
        {
            return redirect()->route('admin.category.show')->with('success', 'Xóa bài viết thành công');
        }
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Category;
use App\Models\Store;

class CategoryController extends Controller
{
    public function index($alias, Request $request) {
        $record = Category::where('slug',$alias)->firstOrFail();
        return view('category.index',compact('record'));
    }
    public function search(Request $request) {
        $query = Store::latest();
        if ($request->keyword) {
            $query->where(function($p)use($request){
                $p->where('title','like','%'.$request->keyword.'%')
                ->orWhere('slug','like','%'.$request->keyword.'%')
                ->orWhere('description','like','%'.$request->keyword.'%')
                ->orWhere('content','like','%'.$request->keyword.'%');
            });
        }
        if ($request->type) {
            $query->where('type_id',$request->type);
        }
        if ($request->position) {
            $query->where('position_id',$request->position);
        }
        $records = $query->paginate(20);
        $keyword = $request->keyword;
        return view('category.search',compact('records','keyword'));
    }
    public function all(Request $request) {
        $query = Store::latest();
        $records = $query->paginate(20);
        return view('category.all',compact('records'));
    }
}

resources/views/category/all.blade.php
@extends('layouts.app')
@section('meta')
<meta name="keywords" content=""/>
<meta name="description" content=""/>
<meta property="og:image" content="{{env('APP_LOGO')}}">
<meta property="og:type" content="website">
<meta property="og:title" content="{{env('APP_NAME')}}">
<meta property="og:description" content="{{env('APP_NAME')}}">
@stop
@section('content')

<section   class="gray-bg hidden-section particles-wrapper">
    <div class="container">
        <div class="section-title">
            <h2>Danh mục</h2>
            <div class="section-subtitle">Tất cả</div>
            <span class="section-separator"></span>
        </div>
    </div>
                            
</section>
<section>
    <div class="container big-container">
        <div class="section-title">
            <h2><span>Danh mục cửa hàng</span></h2>
            <div class="section-subtitle">Danh mục cửa hàng</div>
            <span class="section-separator"></span>
        </div>
        <div class="grid-item-holder gallery-items fl-wrap">
            @include('category.stores',['stores'=>$records])
        </div>
    </div>
</section>
@endsection
@section('scripts')
<script>
    $(function(){
        console.log('Category all ready')
    })
</script>
@endsection

resources/views/category/index.blade.php
@extends('layouts.app')
@section('meta')
<meta name="keywords" content="{{$record->title}}"/>
<meta name="description" content="{{$record->description}}"/>
<meta property="og:image" content="{{env('APP_URL').$record->image}}">
<meta property="og:type" content="website">
<meta property="og:title" content="{{$record->title}}">
<meta property="og:description" content="{{$record->description}}">
@stop
@section('content')

<section   class="gray-bg hidden-section particles-wrapper">
    <div class="container">
        <div class="section-title">
            <h2>{{$record->title}}</h2>
            <div class="section-subtitle">{{$record->title}}</div>
            <span class="section-separator"></span>
            <p>{{$record->description}}</p>
        </div>
        <div class="listing-item-grid_container fl-wrap">
            <div class="row">
                @foreach($record->children as $category)
                <div class="col-sm-4">
                    <div class="listing-item-grid">
                        <div class="bg"  data-bg="{{$category->image?:'/themes/townhub/images/all/56.jpg'}}"></div>
                        <div class="d-gr-sec"></div>
                        <div class="listing-counter color2-bg"><span>{{number_format($category->stores()->count(),0)}}</span> Listings</div>
                        <div class="listing-item-grid_title">
                            <h3><a href="{{$category->url}}">{{$category->title}}</a></h3>
                            <p>{{$category->description}}</p>
                        </div>
                    </div>
                </div>
                @endforeach                                                                                               
            </div>
        </div>

    </div>
                            
</section>
<section>
    <div class="container big-container">
        <div class="section-title">
            <h2><span>Popular Listings</span></h2>
            <div class="section-subtitle">Popular Listings</div>
            <span class="section-separator"></span>
        </div>
        <div class="grid-item-holder gallery-items fl-wrap">
            @include('shared.stores',['stores'=>$record->stores()])
        </div>
    </div>
</section>
@endsection
@section('scripts')
<script>
    $(function(){
        console.log('Category index ready')
    })
</script>
@endsection

resources/views/category/search.blade.php
@extends('layouts.app')
@section('meta')
<meta name="keywords" content="{{$keyword.' - '.env('APP_NAME')}}"/>
<meta name="description" content="{{$keyword.' - '.env('APP_NAME')}}"/>
<meta property="og:image" content="{{env('APP_LOGO')}}">
<meta property="og:type" content="website">
<meta property="og:title" content="{{$keyword.' - '.env('APP_NAME')}}">
<meta property="og:description" content="{{$keyword.' - '.env('APP_NAME')}}">
@stop
@section('content')

<section   class="gray-bg hidden-section particles-wrapper">
    <div class="container">
        <div class="section-title">
            <h2>{{$keyword}}</h2>
            <div class="section-subtitle">Từ khóa</div>
            <span class="section-separator"></span>
        </div>
    </div>
                            
</section>
<section>
    <div class="container big-container">
        <div class="section-title">
            <h2><span>Kết quả tìm kiếm</span></h2>
            <div class="section-subtitle">Kết quả tìm kiếm</div>
            <span class="section-separator"></span>
        </div>
        <div class="grid-item-holder gallery-items fl-wrap">
            @include('category.stores',['stores'=>$records])
        </div>
    </div>
</section>
@endsection
@section('scripts')
<script>
    $(function(){
        console.log('Category search ready')
    })
</script>
@endsection

resources/views/category/stores.blade.php
@foreach($records as $store)
<div class="gallery-item restaurant events">
    <div class="listing-item">
        <article class="geodir-category-listing fl-wrap">
            <div class="geodir-category-img">
                <a href="{{$store->url}}" class="geodir-category-img-wrap fl-wrap">
                    <img src="{{collect($store->banner)->first()?:'/themes/townhub/images/all/1.jpg'}}" alt="{{$store->title}}"> 
                </a>
                <div class="listing-avatar"><a href="{{$store->url}}"><img src="{{$store->avatar?:'/themes/townhub/images/avatar/1.jpg'}}" alt="{{$store->title}}"></a>
                    <span class="avatar-tooltip">Added By  <strong>{{$store->user->name??'anonymous'}}</strong></span>
                </div>
                <div class="geodir-category-opt">
                    <div class="listing-rating-count-wrap">
                        <div class="review-score">4.8</div>
                        <div class="listing-rating card-popup-rainingvis" data-starrating2="5"></div>
                        <br>
                        <div class="reviews-count">12 reviews</div>
                    </div>
                </div>
            </div>
            <div class="geodir-category-content fl-wrap title-sin_item">
                <div class="geodir-category-content-title fl-wrap">
                    <div class="geodir-category-content-title-item">
                        <h3 class="title-sin_map"><a href="{{$store->url}}">{{$store->title}}</a><span class="verified-badge"><i class="fal fa-check"></i></span></h3>
                        <div class="geodir-category-location fl-wrap"><a href="{{$store->url}}" ><i class="fas fa-map-marker-alt"></i> {{$store->address?:'-'}}</a></div>
                    </div>
                </div>
                <div class="geodir-category-text fl-wrap">
                    <p class="small-text">{{$store->description?:'-'}}</p>
                </div>
                <div class="geodir-category-footer fl-wrap">
                    <a class="listing-item-category-wrap">
                        <div class="listing-item-category red-bg"><img  src="{{ asset($store->categories->first()->image??'') }}" alt="{{ $store->categories->first()->title??'' }}"></div>
                        <span>{{ $store->categories->first()->title??'' }}</span>
                    </a>
                    <div class="geodir-opt-list">
                        <ul class="no-list-style">
                            <li><a href="#" class="show_gcc"><i class="fal fa-envelope"></i><span class="geodir-opt-tooltip">Contact Info</span></a></li>
                            <li><a href="#1" class="single-map-item" data-newlatitude="40.72956781" data-newlongitude="-73.99726866"><i class="fal fa-map-marker-alt"></i><span class="geodir-opt-tooltip">On the map <strong>1</strong></span> </a></li>
                            <li>
                                <div class="dynamic-gal gdop-list-link" data-dynamicPath="[{'src': 'images/all/1.jpg'},{'src': 'images/all/24.jpg'}, {'src': 'images/all/12.jpg'}]"><i class="fal fa-search-plus"></i><span class="geodir-opt-tooltip">Gallery</span></div>
                            </li>
                        </ul>
                    </div>
                    <div class="geodir-category_contacts">
                        <div class="close_gcc"><i class="fal fa-times-circle"></i></div>
                        <ul class="no-list-style">
                            <li><span><i class="fal fa-phone"></i> Call : </span><a href="tel:{{str_replace(' ', '', $store->phone)}}">{{$store->phone}}</a></li>
                            <li><span><i class="fal fa-envelope"></i> Write : </span><a href="mailto:{{$store->user->email}}">{{$store->user->email}}</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </article>
    </div>
</div>
@endforeach